### PR TITLE
Fixes issue #4

### PR DESCRIPTION
**Pull request by DominusKelvin**
# Description
- Refactor props to follow Vue naming convention

# Fixes # (issue)
#4 

# What Was Done
+ Refactor props
+ Updated README
+ Removed a prop that was not defined in the component (widget_failed)

# How Do I Test?
- Follow README to rename props

### CODE REVIEW

**Comment by DominusKelvin** [comment]
@eshiett1995 I believe this should fix it.

**Comment by eshiett1995** [comment]
> @eshiett1995 I believe this should fix it.

@DominusKelvin  Seen your changes, this might not fix it, because the props need to be in a specific name for it to work.

**Comment by DominusKelvin** [comment]
Really? Can you please share more light on the matter

**Comment by eshiett1995** [comment]
@DominusKelvin so Okra-vue is a wrapper around okra-js. okra js expects some particular properties namely:
key, token, env, logo, clientName, color, limit, filter, incorporate, connectMessage, guarantors, widget_success, widget_failed, callback_url ,currency, exp, options,onSuccess,onClose. 

that is why didn't change the format. If you look at the code, you would understand better what I stated above.

**Comment by DominusKelvin** [comment]
Yeah I did. My implementation left the options like it was but I changed the props. So you can definitely still have callback_url and callbackUrl prop being assigned to it. It won’t affect the implementation in any way.

**Comment by DominusKelvin** [comment]
Also if you check the ReadMe example usage, you would see widget_failed props but it wasn’t defined in the component. So have a closer look please.

**Comment by eshiett1995** [comment]
@DominusKelvin I would get back to you shortly. Thank you

**Pull request merged**
